"""Filesystem adapters for canonical Work Context data."""

from workctx.adapters.filesystem._paths import ContextZone
from workctx.adapters.filesystem.lock import (
    ContextLock,
    LockFenceError,
    LockHeldError,
    LockInspection,
    LockMetadata,
    inspect_context_lock,
    verify_lock_fence,
)
from workctx.adapters.filesystem.registry import (
    ContextRegistry,
    RegisteredContext,
    RegistryConflictError,
    RegistryError,
    get_active_context,
    list_contexts,
    register_context,
    set_active_context,
    unregister_context,
)
from workctx.adapters.filesystem.serialization import (
    MarkdownDocument,
    dump_json_bytes,
    dump_yaml_bytes,
    has_hand_edits_json,
    has_hand_edits_markdown,
    has_hand_edits_yaml,
    load_json_model,
    load_markdown_model,
    load_yaml_model,
    render_markdown_bytes,
)
from workctx.adapters.filesystem.staging import (
    IntentRecord,
    RecoverableReplaceError,
    RecoveryInspection,
    RecoveryRequiredError,
    RecoveryState,
    ReplaceRetryPolicy,
    StagedReplacement,
    StagedWrite,
    atomic_replace_bytes,
    inspect_recovery,
)
from workctx.adapters.filesystem.store import CanonicalStore

__all__ = [
    "CanonicalStore",
    "ContextLock",
    "ContextRegistry",
    "ContextZone",
    "IntentRecord",
    "LockFenceError",
    "LockHeldError",
    "LockInspection",
    "LockMetadata",
    "MarkdownDocument",
    "RecoverableReplaceError",
    "RecoveryInspection",
    "RecoveryRequiredError",
    "RecoveryState",
    "RegisteredContext",
    "RegistryConflictError",
    "RegistryError",
    "ReplaceRetryPolicy",
    "StagedReplacement",
    "StagedWrite",
    "atomic_replace_bytes",
    "dump_json_bytes",
    "dump_yaml_bytes",
    "get_active_context",
    "has_hand_edits_json",
    "has_hand_edits_markdown",
    "has_hand_edits_yaml",
    "inspect_context_lock",
    "inspect_recovery",
    "list_contexts",
    "load_json_model",
    "load_markdown_model",
    "load_yaml_model",
    "register_context",
    "render_markdown_bytes",
    "set_active_context",
    "unregister_context",
    "verify_lock_fence",
]
