"""Declarative connector manifests and generic snapshot synchronization."""

from workctx.connectors.errors import (
    ConnectorConnectionError,
    ConnectorError,
    ConnectorManifestError,
    ConnectorNotFoundError,
    ConnectorRedirectError,
    ConnectorRegistrationError,
    ConnectorSecretExposureError,
    ConnectorSecretResolutionError,
    ConnectorSizeLimitError,
    ConnectorSnapshotError,
    ConnectorSnapshotNotFoundError,
    ConnectorStatusError,
    ConnectorTimeoutError,
    ConnectorWriteError,
    DuplicateConnectorNameError,
)
from workctx.connectors.manifests import CONNECTOR_DIRECTORY, load_manifests
from workctx.connectors.models import (
    DEFAULT_MAX_BYTES,
    DEFAULT_TIMEOUT_SECONDS,
    MAX_MAX_BYTES,
    MAX_TIMEOUT_SECONDS,
    ConnectorManifest,
    ConnectorSnapshotStatus,
    ConnectorStatusResult,
    ConnectorSyncError,
    ConnectorSyncFailureKind,
    ConnectorSyncOutcome,
    ProvenanceSecretRef,
    SnapshotManifest,
    SnapshotProvenance,
    SnapshotSchedule,
    SnapshotSyncDisposition,
    SnapshotSyncResult,
    SyncAllResult,
    SyncResult,
)
from workctx.connectors.runtime import Clock, connector_status, status, sync, sync_all
from workctx.connectors.state import LAST_SYNC_STATE_PATH

__all__ = [
    "CONNECTOR_DIRECTORY",
    "DEFAULT_MAX_BYTES",
    "DEFAULT_TIMEOUT_SECONDS",
    "LAST_SYNC_STATE_PATH",
    "MAX_MAX_BYTES",
    "MAX_TIMEOUT_SECONDS",
    "Clock",
    "ConnectorConnectionError",
    "ConnectorError",
    "ConnectorManifest",
    "ConnectorManifestError",
    "ConnectorNotFoundError",
    "ConnectorRedirectError",
    "ConnectorRegistrationError",
    "ConnectorSecretExposureError",
    "ConnectorSecretResolutionError",
    "ConnectorSizeLimitError",
    "ConnectorSnapshotError",
    "ConnectorSnapshotNotFoundError",
    "ConnectorSnapshotStatus",
    "ConnectorStatusError",
    "ConnectorStatusResult",
    "ConnectorSyncError",
    "ConnectorSyncFailureKind",
    "ConnectorSyncOutcome",
    "ConnectorTimeoutError",
    "ConnectorWriteError",
    "DuplicateConnectorNameError",
    "ProvenanceSecretRef",
    "SnapshotManifest",
    "SnapshotProvenance",
    "SnapshotSchedule",
    "SnapshotSyncDisposition",
    "SnapshotSyncResult",
    "SyncAllResult",
    "SyncResult",
    "connector_status",
    "load_manifests",
    "status",
    "sync",
    "sync_all",
]
