"""Project-scoped adapters for Codex, Claude Code, and Gemini CLI."""

from .detection import (
    PROJECT_MARKERS,
    SUPPORTED_VERSION_RANGES,
    ClientDetector,
    detect_client,
    detect_clients,
    parse_client_version,
)
from .errors import (
    AdapterConflictError,
    AdapterInvalidError,
    AgentAdapterError,
    AgentUnavailableError,
    InvalidAdapterStateError,
    InvalidApprovalError,
    RecoveryConflictError,
    RecoveryRequiredError,
    UnsupportedClientVersionError,
)
from .models import (
    AdapterPlan,
    AdapterState,
    AdapterStatus,
    AgentClient,
    ClientAvailability,
    ClientCapability,
    DriftDetail,
    DriftReason,
    FeatureState,
    FeatureStatus,
    FileOperation,
    OpenedContext,
    OperationAction,
    OperationResult,
    PersonalizationLayerName,
    PersonalizationLayerStatus,
    PlannedChange,
    SemanticVersion,
    SourceOrigin,
    SupportedVersionRange,
    TargetApproval,
)
from .personalization import (
    PERSONALIZATION_END_MARKER,
    PERSONALIZATION_FILENAME,
    PERSONALIZATION_LAYER_MAX_BYTES,
    PERSONALIZATION_START_MARKER,
    PersonalizationEncodingError,
    PersonalizationLayer,
    PersonalizationLayerError,
    PersonalizationLayers,
    PersonalizationLayerTooLargeError,
    PersonalizationSecretError,
    load_personalization_layers,
    render_personalization_section,
    render_personalized_bridge,
    user_personalization_path,
)
from .service import AgentAdapterService
from .session import open_context

AgentAdapterManager = AgentAdapterService
ComponentStatus = FeatureStatus

__all__ = [
    "PERSONALIZATION_END_MARKER",
    "PERSONALIZATION_FILENAME",
    "PERSONALIZATION_LAYER_MAX_BYTES",
    "PERSONALIZATION_START_MARKER",
    "PROJECT_MARKERS",
    "SUPPORTED_VERSION_RANGES",
    "AdapterConflictError",
    "AdapterInvalidError",
    "AdapterPlan",
    "AdapterState",
    "AdapterStatus",
    "AgentAdapterError",
    "AgentAdapterManager",
    "AgentAdapterService",
    "AgentClient",
    "AgentUnavailableError",
    "ClientAvailability",
    "ClientCapability",
    "ClientDetector",
    "ComponentStatus",
    "DriftDetail",
    "DriftReason",
    "FeatureState",
    "FeatureStatus",
    "FileOperation",
    "InvalidAdapterStateError",
    "InvalidApprovalError",
    "OpenedContext",
    "OperationAction",
    "OperationResult",
    "PersonalizationEncodingError",
    "PersonalizationLayer",
    "PersonalizationLayerError",
    "PersonalizationLayerName",
    "PersonalizationLayerStatus",
    "PersonalizationLayerTooLargeError",
    "PersonalizationLayers",
    "PersonalizationSecretError",
    "PlannedChange",
    "RecoveryConflictError",
    "RecoveryRequiredError",
    "SemanticVersion",
    "SourceOrigin",
    "SupportedVersionRange",
    "TargetApproval",
    "UnsupportedClientVersionError",
    "detect_client",
    "detect_clients",
    "load_personalization_layers",
    "open_context",
    "parse_client_version",
    "render_personalization_section",
    "render_personalized_bridge",
    "user_personalization_path",
]
