from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from workctx.adapters.agents._safe_fs import SafeRoot
from workctx.adapters.agents.errors import AdapterConflictError, InvalidAdapterStateError
from workctx.adapters.agents.models import (
    AdapterState,
    AgentClient,
    FileOperation,
)
from workctx.adapters.agents.renderers import content_hash
from workctx.adapters.agents.service import AgentAdapterService

_SKILL_NAME = "fixture-skill"


def _service() -> AgentAdapterService:
    return AgentAdapterService(
        executable_finder=lambda name: f"fake-{name}",
        version_probe=lambda executable, _root: {
            "fake-codex": "0.5.0",
            "fake-claude": "2.0.0",
            "fake-gemini": "0.5.0",
        }[executable],
        session_id_factory=lambda: "test-session",
    )


def _install(service: AgentAdapterService, project: Path) -> None:
    service.install(service.plan_install(project, AgentClient.CLAUDE))


def _uninstall(service: AgentAdapterService, project: Path) -> None:
    service.uninstall(service.plan_uninstall(project, AgentClient.CLAUDE))


def _write_local_source(project: Path) -> None:
    skill = project / ".agents" / "skills" / _SKILL_NAME / "SKILL.md"
    skill.parent.mkdir(parents=True)
    (project / ".agents" / "skills" / "registry.yaml").write_text(
        f"schema_version: 1\nskills:\n  - id: {_SKILL_NAME}\n    side_effect_class: read_only\n",
        encoding="utf-8",
    )
    skill.write_text(
        "---\n"
        f"name: {_SKILL_NAME}\n"
        "description: Use when exercising isolated security behavior in tests.\n"
        "---\n\n"
        "# Fixture skill\n",
        encoding="utf-8",
    )


def _manifest_path(project: Path) -> Path:
    return project / ".workctx" / "agent-adapters" / "claude" / "skill-manifest.json"


def test_modified_generated_target_is_report_only_and_never_backed_up_or_replaced(
    tmp_path: Path,
) -> None:
    project = tmp_path / "project"
    project.mkdir()
    _write_local_source(project)
    service = _service()
    _install(service, project)
    target = project / ".claude" / "skills" / _SKILL_NAME / "SKILL.md"
    modified = b"operator-owned modification\n"
    target.write_bytes(modified)

    status = service.status(project, AgentClient.CLAUDE)
    plan = service.plan_repair(project, AgentClient.CLAUDE)

    assert status.state is AdapterState.CONFLICT
    assert status.repair_blocked
    assert plan.blocked_reason is not None
    assert {change.operation for change in plan.changes} == {FileOperation.PRESERVE}
    assert all(not change.requires_approval for change in plan.changes)
    with pytest.raises(AdapterConflictError):
        service.repair(plan)
    assert target.read_bytes() == modified
    assert not (project / ".workctx" / "backups").exists()


def test_changed_target_and_matching_forged_manifest_hash_remain_a_conflict(
    tmp_path: Path,
) -> None:
    project = tmp_path / "project"
    project.mkdir()
    _write_local_source(project)
    service = _service()
    _install(service, project)
    target = project / ".claude" / "skills" / _SKILL_NAME / "SKILL.md"
    forged_content = b"forged generated bytes\n"
    target.write_bytes(forged_content)
    manifest_path = _manifest_path(project)
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest["skills"][0]["generated"][0]["content_hash"] = content_hash(forged_content)
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    status = service.status(project, AgentClient.CLAUDE)
    repair = service.plan_repair(project, AgentClient.CLAUDE)
    uninstall = service.plan_uninstall(project, AgentClient.CLAUDE)

    assert status.state is AdapterState.CONFLICT
    assert status.repair_blocked
    assert any("authenticated" in warning for warning in status.warnings)
    for plan in (repair, uninstall):
        assert plan.blocked_reason is not None
        assert {change.operation for change in plan.changes} == {FileOperation.PRESERVE}
        assert all(not change.requires_approval for change in plan.changes)


def test_unsafe_symlink_target_causes_zero_writes(
    tmp_path: Path,
) -> None:
    project = tmp_path / "project"
    outside = tmp_path / "outside"
    project.mkdir()
    outside.mkdir()
    _write_local_source(project)
    target_parent = project / ".claude" / "skills" / _SKILL_NAME
    target_parent.mkdir(parents=True)
    outside_target = outside / "victim.md"
    outside_target.write_bytes(b"outside canary\n")
    link = target_parent / "SKILL.md"
    try:
        link.symlink_to(outside_target)
    except OSError as error:
        pytest.skip(f"symlink creation is unavailable: {error}")

    with pytest.raises(InvalidAdapterStateError):
        _service().plan_install(project, AgentClient.CLAUDE)

    assert outside_target.read_bytes() == b"outside canary\n"
    assert link.is_symlink()
    assert not (project / "CLAUDE.md").exists()
    assert not _manifest_path(project).exists()


def test_unmanaged_symlink_is_warning_only_with_or_without_manifest(tmp_path: Path) -> None:
    project = tmp_path / "project"
    outside = tmp_path / "outside.txt"
    project.mkdir()
    outside.write_bytes(b"outside canary\n")
    _write_local_source(project)
    service = _service()
    _install(service, project)
    link = project / ".claude" / "skills" / "operator-link.md"
    try:
        link.symlink_to(outside)
    except OSError as error:
        pytest.skip(f"symlink creation is unavailable: {error}")

    installed = service.status(project, AgentClient.CLAUDE)
    _uninstall(service, project)
    uninstalled = service.status(project, AgentClient.CLAUDE)

    warning = "Unmanaged unsafe adapter entry: .claude/skills/operator-link.md"
    assert installed.state is AdapterState.CURRENT
    assert warning in installed.warnings
    assert uninstalled.state is AdapterState.NOT_INSTALLED
    assert warning in uninstalled.warnings
    assert link.is_symlink()
    assert outside.read_bytes() == b"outside canary\n"


def test_uninstall_does_not_traverse_linked_canonical_tree(
    tmp_path: Path,
) -> None:
    project = tmp_path / "project"
    outside = tmp_path / "outside"
    project.mkdir()
    outside.mkdir()
    _write_local_source(project)
    service = _service()
    _install(service, project)
    target = project / ".claude" / "skills" / _SKILL_NAME / "SKILL.md"
    manifest = _manifest_path(project)
    skills = project / ".agents" / "skills"
    skills.rename(project / ".agents" / "original-skills")
    try:
        skills.symlink_to(outside, target_is_directory=True)
    except OSError as error:
        pytest.skip(f"directory symlink creation is unavailable: {error}")

    plan = service.plan_uninstall(project, AgentClient.CLAUDE)
    service.uninstall(plan)

    assert not target.exists()
    assert not manifest.exists()
    assert skills.is_symlink()
    assert tuple(outside.iterdir()) == ()


@pytest.mark.parametrize("client", tuple(AgentClient))
def test_full_service_lifecycle_never_reads_or_emits_fake_user_global_auth(
    tmp_path: Path,
    monkeypatch: Any,
    client: AgentClient,
) -> None:
    project = tmp_path / "project"
    fake_home = tmp_path / "fake-home"
    project.mkdir()
    fake_home.mkdir(exist_ok=True)
    _write_local_source(project)
    for relative in (
        ".codex/auth.json",
        ".claude/.credentials.json",
        ".gemini/oauth_creds.json",
    ):
        path = fake_home / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(b"GLOBAL-AUTH-CANARY")
    monkeypatch.setenv("HOME", str(fake_home))
    monkeypatch.setenv("USERPROFILE", str(fake_home))

    def reject_home(_cls: type[Path]) -> Path:
        raise AssertionError("service attempted to resolve user-global state")

    monkeypatch.setattr(Path, "home", classmethod(reject_home))
    service = _service()
    service.install(service.plan_install(project, client))
    status = service.status(project, client)
    project_outputs = tuple(
        path.read_bytes() for path in project.rglob("*") if path.is_file() and not path.is_symlink()
    )
    service.uninstall(service.plan_uninstall(project, client))

    assert status.state is AdapterState.CURRENT
    assert all(b"GLOBAL-AUTH-CANARY" not in content for content in project_outputs)
    assert all(path.read_bytes() == b"GLOBAL-AUTH-CANARY" for path in fake_home.rglob("*.json"))


def test_credential_capable_canonical_resource_is_rejected_before_leaf_read(
    tmp_path: Path,
    monkeypatch: Any,
) -> None:
    project = tmp_path / "project"
    project.mkdir()
    _write_local_source(project)
    sensitive = project / ".agents" / "skills" / _SKILL_NAME / "token.txt"
    sensitive.write_bytes(b"RESOURCE-CANARY")
    original = SafeRoot.inspect_file

    def reject_sensitive_read(self: SafeRoot, relative_path: str) -> Any:
        if relative_path.endswith("/token.txt"):
            raise AssertionError("credential-capable resource bytes were inspected")
        return original(self, relative_path)

    monkeypatch.setattr(SafeRoot, "inspect_file", reject_sensitive_read)

    with pytest.raises(InvalidAdapterStateError, match="credential-capable resource path"):
        _service().plan_install(project, AgentClient.CLAUDE)


def test_credential_capable_manifest_target_is_rejected_before_leaf_read(
    tmp_path: Path,
    monkeypatch: Any,
) -> None:
    project = tmp_path / "project"
    project.mkdir()
    _write_local_source(project)
    service = _service()
    _install(service, project)
    manifest_path = _manifest_path(project)
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest["skills"][0]["generated"].append(
        {
            "path": ".claude/skills/fixture-skill/token.txt",
            "content_hash": content_hash(b"MANIFEST-CANARY"),
        }
    )
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    original = SafeRoot.inspect_file

    def reject_sensitive_read(self: SafeRoot, relative_path: str) -> Any:
        if relative_path.endswith("/token.txt"):
            raise AssertionError("credential-capable manifest target bytes were inspected")
        return original(self, relative_path)

    monkeypatch.setattr(SafeRoot, "inspect_file", reject_sensitive_read)

    assert service.status(project, AgentClient.CLAUDE).state is AdapterState.INVALID


def test_manifest_validation_precedes_unsupported_client_version(tmp_path: Path) -> None:
    project = tmp_path / "project"
    manifest = _manifest_path(project)
    manifest.parent.mkdir(parents=True)
    manifest.write_bytes(b"not-json\n")
    service = AgentAdapterService(
        executable_finder=lambda name: f"fake-{name}",
        version_probe=lambda _executable, _root: "99.0.0",
    )

    status = service.status(project, AgentClient.CLAUDE)

    assert status.state is AdapterState.INVALID
    assert status.repair_blocked


def test_unhashable_registry_key_stays_inside_typed_status_and_plan_boundaries(
    tmp_path: Path,
) -> None:
    project = tmp_path / "project"
    project.mkdir()
    _write_local_source(project)
    service = _service()
    _install(service, project)
    (project / ".agents" / "skills" / "registry.yaml").write_bytes(b"? [a, b]\n: bad\n")

    status = service.status(project, AgentClient.CLAUDE)

    assert status.state is AdapterState.INVALID
    assert any(item.reason.value == "registry_invalid" for item in status.drift)
    with pytest.raises(InvalidAdapterStateError):
        service.plan_repair(project, AgentClient.CLAUDE)
