"""Deterministic transaction, audit-ledger, and recovery APIs."""

from workctx.transactions.engine import (
    TransactionEngine,
    apply,
    dry_run,
    recover,
    validate_proposal,
)
from workctx.transactions.errors import (
    DuplicateProposalError,
    LedgerIntegrityError,
    PostconditionRollbackError,
    PreimageChangedError,
    ProposalValidationError,
    ReceiptAuthenticationError,
    RecoveryPendingError,
    StaleRevisionError,
    TransactionConflictError,
    TransactionError,
)
from workctx.transactions.ledger import (
    AuditSummary,
    LedgerVerification,
    audit_summary,
    authenticate_apply_result,
    read_audit_events,
    verify_ledger,
)
from workctx.transactions.models import (
    ApplyResult,
    DiagnosticSeverity,
    DryRunResult,
    OperationEffect,
    ProjectionState,
    ProjectionStatus,
    ProposalValidationResult,
    RecoveryResult,
    RecoveryStrategy,
    TransactionDiagnostic,
)

__all__ = [
    "ApplyResult",
    "AuditSummary",
    "DiagnosticSeverity",
    "DryRunResult",
    "DuplicateProposalError",
    "LedgerIntegrityError",
    "LedgerVerification",
    "OperationEffect",
    "PostconditionRollbackError",
    "PreimageChangedError",
    "ProjectionState",
    "ProjectionStatus",
    "ProposalValidationError",
    "ProposalValidationResult",
    "ReceiptAuthenticationError",
    "RecoveryPendingError",
    "RecoveryResult",
    "RecoveryStrategy",
    "StaleRevisionError",
    "TransactionConflictError",
    "TransactionDiagnostic",
    "TransactionEngine",
    "TransactionError",
    "apply",
    "audit_summary",
    "authenticate_apply_result",
    "dry_run",
    "read_audit_events",
    "recover",
    "validate_proposal",
    "verify_ledger",
]
